substitutions:
  name: esphome-web-b45f2c
  friendly_name: ESPHome WROVER-E 2

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

# BMP180 Baro-sensor, word toegevoegd als bmp085
# 
# Configuratie variabelen:
# temperature (Optional): The information for the temperature sensor.
# pressure (Optional): The information for the pressure sensor.
# address (Optional, int): Manually specify the I²C address of the sensor. Defaults to 0x77.
# update_interval (Optional, Time): The interval to check the sensor. Defaults to 60s.

# Voor de BMP180 moet je I2C configureren. Ik weet niet of
# id: bus_a noodzakelijk is, hoewel een ESP32 wel twee I2C bussen aankan
# Het werkt in ieder geval wel, in het sensor gedeelte heb ik geen id aangegeven (als dat al mogelijk was)
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

sensor:
  - platform: bmp085
    temperature:
      name: "tuinhuis-temp"
    pressure:
      name: "tuinhuis-druk"
    update_interval: 120s